version: '3.8'

services:
  postgres:
    image: docker.io/library/postgres:17-alpine
    container_name: release-manager-db
    environment:
      POSTGRES_DB: releasemanager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U releasemanager"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - release-manager-dev

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: release-manager-keycloak-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: releasemanager
      KC_DB_PASSWORD: releasemanager123
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8180:8080"
    volumes:
      - ./infrastructure/keycloak:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
      - --hostname-strict=false
      - --hostname-strict-https=false
      - --http-enabled=true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - release-manager-dev

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: release-manager-azurite-dev
    environment:
      AZURITE_ACCOUNTS: devstorageaccount1:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data_dev:/data
    command: azurite --loose --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0
    networks:
      - release-manager-dev

volumes:
  postgres_data_dev:
    driver: local
  azurite_data_dev:
    driver: local

networks:
  release-manager-dev:
    driver: bridge
