version: "3.8"
services:
  db:
    image: postgres:17-alpine
    container_name: release-manager-db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  default:
    name: release-manager-net
    external: true
