version: "3.8"
services:
  db:
    image: postgres:17-alpine
    container_name: release-manager-db
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: release-manager-pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8484:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  default:
    name: release-manager-net
    external: true
