version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: release-manager-db
    environment:
      POSTGRES_DB: release_manager_db
      POSTGRES_USER: releasemanager
      POSTGRES_PASSWORD: releasemanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U releasemanager -d release_manager_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: release-manager-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    command:
      - "start-dev"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
