# Database Configuration
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/releasemanager_it
quarkus.arc.dev-mode.monitoring-enabled=true
quarkus.log.category."io.quarkus.arc".level=DEBUG