package com.releasemanager.domain.model;

public enum ReleaseStatus {
    MR_APROVADO,
    FALHA_BUILD_TESTE,
    PARA_TESTE_SISTEMA,
    REPROVADA_TESTE,
    APROVADA_TESTE,
    FALHA_BUILD_PRODUCAO,
    PARA_TESTE_REGRESSIVO,
    FALHA_INSTALACAO_ESTAVEL,
    INTERNO,
    REVOGADA,
    REPROVADA_TESTE_REGRESSIVO,
    APROVADA_TESTE_REGRESSIVO,
    CONTROLADA,
    DISPONIVEL
}
